spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: ***REMOVED***
        credential:
          client-id: ***REMOVED***
          client-secret:
        app-id-uri: api://***REMOVED***
        application-type: web_application_and_resource_server
        authorization-clients:
          graph:
            authorizationGrantType: authorization_code
            scopes:
              - https://graph.microsoft.com/User.Read.All
              - https://graph.microsoft.com/Directory.Read.All
  datasource:
    url: jdbc:postgresql://localhost:5432/students
    username: postgres
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect