spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: ***REMOVED***
        credential:
          client-id: ***REMOVED***
  datasource:
    url: jdbc:postgresql://localhost:5432/students
    username: postgres
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect