spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: 21716e18-9a39-4436-8fdf-d670c9aaeba3
        credential:
          client-id: 504c0fe0-0a8f-4286-850a-a5c25f27c0fd
        app-id-uri: api://504c0fe0-0a8f-4286-850a-a5c25f27c0fd
  datasource:
    url: jdbc:postgresql://localhost:5432/students
    username: postgres
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect