spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: c4e7abab-c7fa-4661-8c32-afd5aaab4496
        credential:
          client-id: 15093605-5712-4251-bc3b-14533cabd46f
        app-id-uri: api://15093605-5712-4251-bc3b-14533cabd46f
  datasource:
    url: jdbc:postgresql://localhost:5432/students
    username: postgres
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect